sensor:
  - platform: pmsx003
    type: PMS5003ST
    pm_1_0_std:
      name: ${Particulate_Matter_1_0um_Concentration_at_standard_particle}
      id: pm_1_0_std 
    pm_2_5_std:
      name: ${Particulate_Matter_2_5um_Concentration_at_standard_particle}
      id: pm_2_5_std 
    pm_10_0_std:
      name: ${Particulate_Matter_10_0um_Concentration_at_standard_particle}
      id: pm_10_0_std  
    pm_1_0:
      name: "${Particulate_Matter_1_0um_Concentration_under_atmospheric_environment}"
      id: pm_1_0
    pm_2_5:
      name: "${Particulate_Matter_2_5um_Concentration_under_atmospheric_environment}"
      id: pm_2_5
    pm_10_0:
      name: "${Particulate_Matter_10_0um_Concentration_under_atmospheric_environment}"
      id: pm_10_0
    pm_0_3um:
      name: "${Particles_0_3um_0_1L_air}"
      id: pm_0_3um
    pm_0_5um:
      name: "${Particles_0_5um_0_1L_air}"
      id: pm_0_5um
    pm_1_0um:
      name: "${Particles_1_0um_0_1L_air}"
      id: pm_1_0um
    pm_2_5um:
      name: "${Particles_2_5um_0_1L_air}"
      id: pm_2_5um
    pm_5_0um:
      name: "${Particles_5_0um_0_1L_air}"
      id: pm_5_0um
    pm_10_0um:
      name: "${Particles_10_0um_0_1L_air}"
      id: pm_10_0um
    formaldehyde:
      name: ${Formaldehyde}
      id: formaldehyde
    temperature:
      #name: "${device_name} ${Temperature}"
      id: pms-temp
      internal: true
    humidity:
      #name: "${device_name} ${Humidity}"
      id: pms-hum
      internal: true
    update_interval: 120s
    uart_id: PMSX003