substitutions:
  device_name: ps
  device_friendlyname: PowerSwitch
  device_discription: "power switch"

bk72xx:
  board: generic-bk7231n-qfn32-tuya

esphome:
  name: ${device_name}
  friendly_name: ${device_friendlyname}
  comment: "${device_discription}"
  name_add_mac_suffix: true
  project:
    name: heronet.${device_name}
    version: ${version}

wifi:
  # Remove leading '#' and fill in your wifi details
  #ssid: !secret wifi_ssid
  #password: !secret wifi_password
  # Remove leading '#' if you want to a hidden ssid
  #fast_connect: True

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    ap_timeout: 10s

api:

dashboard_import:
  package_import_url: github://heronetnl/Herotools/Powerswitch.yaml@main
  import_full_config: true

packages:
  remote_package:
    url: https://github.com/heronetnl/herotools/
    ref: main
    files:
      # Get basic file
      - Scripts/Basic.yaml

      # Get language file
      - Scripts/Language/nl-NL.yaml

      # 
      - scripts/Devices/Kruitvat/Powerswitch/1-polig.yaml

    refresh: 0d