substitutions:
  # basic file
  Uptime: "Uptime"
  Wifi_signal: "Wifi singal"
  Ip_address: "IP-address"
  Network: "Network"
  Mac_address: "MAC-address"
  Restart: "Restart device"
  Shutdown: "shutdown device"
  Factory_reset: "Factory reset"
  error: "error"

  # Environmental
  Temperature: "Temperature"
  Humidity: "Humidity"
  Pressure: "Pressure"
  Absolute_humidity: "Absolute humidity"
  Dew_point: "Dew point"
  Air_quality: "Air quality"
  Formaldehyde: "Formaldehyde"

  # Pms
  # Particulate Matter <1.0µm Concentration at standard particle
  Particulate_Matter_1_0um_Concentration_at_standard_particle: "Particulate Matter <1.0µm Concentration at standard particle"
  Particulate_Matter_2_5um_Concentration_at_standard_particle: "Particulate Matter <2.5µm Concentration at standard particle"
  Particulate_Matter_10_0um_Concentration_at_standard_particle: "Particulate Matter <10.0µm Concentration at standard particle"

  # Particulate Matter <1.0µm Concentration under atmospheric environment
  Particulate_Matter_1_0um_Concentration_under_atmospheric_environment: "Particulate Matter <1.0µm Concentration under atmospheric environment"
  Particulate_Matter_2_5um_Concentration_under_atmospheric_environment: "Particulate Matter <2.5µm Concentration under atmospheric environment"
  Particulate_Matter_10_0um_Concentration_under_atmospheric_environment: "Particulate Matter <10.0µm Concentration under atmospheric environment"

  # Particles > 0.3um / 0.1L air
  Particles_0_3um_0_1L_air: "Particles > 0.3um / 0.1L air"
  Particles_0_5um_0_1L_air: "Particles > 0.5um / 0.1L air"
  Particles_1_0um_0_1L_air: "Particles > 1.0um / 0.1L air"
  Particles_2_5um_0_1L_air: "Particles > 2.5um / 0.1L air"
  Particles_5_0um_0_1L_air: "Particles > 5.0um / 0.1L air"
  Particles_10_0um_0_1L_air: "Particles > 10.0um / 0.1L air"

  # Air Quality
  Excellent: "Excellent"
  Good: "Good"
  Lightly_polluted: "Lightly polluted"
  Moderately_polluted: "Moderately polluted"
  Heavily_polluted: "Heavily polluted"
  Severely_polluted: "Severely polluted"
  Extremely_polluted: "Extremely polluted"