substitutions:
  # basic file
  Uptime: "Uptime"
  Wifi_signal: "Wifi signaal"
  Ip_address: "IP-adres"
  Network: "Netwerk"
  Mac_address: "MAC-adres"
  Restart: "Opnieuw opstarten"
  Shutdown: "Afsluiten"
  Factory_reset: "Fabrieksinstellingen"
  error: "error"

  # Environmental
  Temperature: "Temperatuur"
  Humidity: "Vochtigheid"
  Pressure: "Lucht druk"
  Absolute_humidity: "Absolute luchtvochtigheid"
  Dew_point: "Dauwpunt"
  Air_quality: "Luchtkwaliteit"
  Formaldehyde: "Formaldehyde"

  # Pms
  # Particulate Matter <1.0µm Concentration at standard particle
  Particulate_Matter_1_0um_Concentration_at_standard_particle: "Fijnstof <1,0 µm Concentratie bij standaarddeeltjes"
  Particulate_Matter_2_5um_Concentration_at_standard_particle: "Fijnstof <2,5 µm Concentratie bij standaarddeeltjes"
  Particulate_Matter_10_0um_Concentration_at_standard_particle: "Fijnstof <10,0 µm Concentratie bij standaarddeeltjes"

  # Particulate Matter <1.0µm Concentration under atmospheric environment
  Particulate_Matter_1_0um_Concentration_under_atmospheric_environment: "Fijnstof <1,0 µm Concentratie onder atmosferische omgeving"
  Particulate_Matter_2_5um_Concentration_under_atmospheric_environment: "Fijnstof <2,5 µm Concentratie onder atmosferische omgeving"
  Particulate_Matter_10_0um_Concentration_under_atmospheric_environment: "Fijnstof <10,0 µm Concentratie onder atmosferische omgeving"

  # Particles > 0.3um / 0.1L air
  Particles_0_3um_0_1L_air: "Deeltjes > 0,3um / 0,1L lucht"
  Particles_0_5um_0_1L_air: "Deeltjes > 0,5um / 0,1L lucht"
  Particles_1_0um_0_1L_air: "Deeltjes > 1,0um / 0,1L lucht"
  Particles_2_5um_0_1L_air: "Deeltjes > 2,5um / 0,1L lucht"
  Particles_5_0um_0_1L_air: "Deeltjes > 5,0um / 0,1L lucht"
  Particles_10_0um_0_1L_air: "Deeltjes > 10,0um / 0,1L lucht"

  # Air Quality
  Excellent: "Uitstekend"
  Good: "Goed"
  Lightly_polluted: "Licht vervuild"
  Moderately_polluted: "Matig vervuild"
  Heavily_polluted: "Zwaar vervuild"
  Severely_polluted: "Ernstig vervuild"
  Extremely_polluted: "Extreem vervuild"