sensor:
  # BMP085 sensor for temperature, pressure and humidity.
  # temperature and humidity data wil not be send to homeassistent
  - platform: bmp085
    temperature:
      #name: "${device_name} ${Temperature}"
      id: bme_temp
      internal: true
      unit_of_measurement: ${TM}
      oversampling: 16x
    pressure:
      name: "${device_name} ${Pressure}"
      id: bme_pres
    i2c_id: i2c_1
    address: 0x77
    update_interval: 30s