sensor:

  # BME280 sensor for temperature, pressure and humidity.
	# temperature and humidity data wil not be send to homeassistent
  - platform: bmp280
		temperature:
			#name: "${device_name} ${Temperature}"
			id: bme-temp
			internal: true
			unit_of_measurement: ${TM}
			oversampling: 16x
		pressure:
			name: "${device_name} ${Pressure}"
			id: bme-pres
		i2c_id: i2c_1
		address: 0x77
		update_interval: 30s