api:
  services:
    - service: "set_sgp30_eco2_baseline"
      variables:
        Eco2_baseline: int
      then:
        - globals.set:
            id: sgp30_eco2_baseline
            value: !lambda "return String(Eco2_baseline, HEX)"

globals:
  - id: sgp30_eco2_baseline
    type: int
    restore_value: yes

  - id: sgp30_tvoc_baseline
    type: int
    restore_value: yes

sensor:
  # SGP30 CO₂ and Volatile Organic Compound Sensor
  - platform: sgp30
    eco2:
      name: "eCO2"
      id: eco2
      accuracy_decimals: 1
    tvoc:
      name: "TVOC"
      id: tvoc
      accuracy_decimals: 1
    store_baseline: yes
    i2c_id: i2c_1
    address: ${I2C_SGP30}
    update_interval: 1s
    baseline:
      eco2_baseline: 0x86C5  ## need to change auto
      tvoc_baseline: 0x8B38  ## need to change auto
    compensation:
      temperature_source: temperature
      humidity_source: humidity
    eco2_baseline:
      id: eco2baseline
      internal: true
    tvoc_baseline:
      id: tvocbaseline
      internal: true