substitutions:
  version: "0.0.1"

logger:
  baud_rate: 0

sensor:
  - platform: template
    name: "${Temperature}"
    id: temperature
    lambda: |-
      if (to_string("${Use_Temp}") == "DS18B20"){
        return id(DS18B20_temp).state;
      }
      else if (to_string("${Use_Temp}") == "AHT"){
        return id(aht_temp).state;
      }
      else if (to_string("${Use_Temp}") == "BME"){
        return id(bme_temp).state;
      }
      else {
        return -99;
      }
    unit_of_measurement: ${TM}

  - platform: template
    name: "${Humidity}"
    id: humidity
    lambda: |-
      if(to_string("${Use_Hum}") == "AHT"){
        return id(aht_hum).state;
      }
      else if (to_string("${Use_Hum}") == "BME"){
        return id(bme_hum).state;
      }
      else {
        return -99;
      }
    unit_of_measurement: "%"
    device_class: "humidity"
    accuracy_decimals: 0
    icon: 'mdi:water-percent'

  - platform: template
    name: "${Pressure}"
    id: pressure
    lambda: |-
      if (to_string("${USE_BME}") == "true"){
        return id(bme_pres).state;
      }
      else {
        return -99999;
      }
    unit_of_measurement: "hPa"
    device_class: "pressure"
    icon: 'mdi:gauge'

  # Absolute Humidity
  - platform: absolute_humidity
    name: "${Absolute_humidity}"
    id: Absolute_Humidity
    temperature: temperature
    humidity: humidity

  # Dew point
  - platform: template
    name: "${Dew_point}"
    id: Dew_Point
    lambda: |-
      return (243.5*(log(id(humidity).state/100)+((17.67*id(temperature).state)/
      (243.5+id(temperature).state)))/(17.67-log(id(humidity).state/100)-
      ((17.67*id(temperature).state)/(243.5+id(temperature).state))));
    unit_of_measurement: °C
    icon: 'mdi:thermometer-alert'

# Text_sensoren
text_sensor:

  # IAQ Classification
  - platform: template
    name: "${Air_quality}"
    icon: "mdi:seed"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        if ( int(id(tvoc).state) <= 65) {
          return to_string("${Excellent}");
        }
        else if ( int(id(tvoc).state) >= 66 && int(id(tvoc).state) <= 220){
          return to_string("${Good}");
        }
        else if ( int(id(tvoc).state) >= 221 && int(id(tvoc).state) <= 660){
          return to_string("${Lightly_polluted}");
        }
        else if ( int(id(tvoc).state) >= 661 && int(id(tvoc).state) <= 1430){
          return to_string("${Moderately_polluted}");
        }
        else if ( int(id(tvoc).state) >= 1431 && int(id(tvoc).state) <= 2200){
          return to_string("${Heavily_polluted}");
        }
        else if ( int(id(tvoc).state) >= 2201 && int(id(tvoc).state) <= 3300){
          return to_string("${Severely_polluted}");
        }
        else if ( int(id(tvoc).state) >= 3301){
          return to_string("${Extremely_polluted}");
        }
        else {
          return to_string("${error}");
        }
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        if ( int(id(tvoc).state) <= 220){
          return to_string("${Good}");
        }
        else if ( int(id(tvoc).state) >= 221 && int(id(tvoc).state) <= 660){
          return to_string("${Lightly_polluted}");
        }
        else if ( int(id(tvoc).state) >= 661 && int(id(tvoc).state) <= 1430){
          return to_string("${Moderately_polluted}");
        }
        else if ( int(id(tvoc).state) >= 1431 && int(id(tvoc).state) <= 2200){
          return to_string("${Heavily_polluted}");
        }
        else if ( int(id(tvoc).state) >= 2201 && int(id(tvoc).state) <= 3300){
          return to_string("${Severely_polluted}");
        }
        else if ( int(id(tvoc).state) >= 3301){
          return to_string("${Extremely_polluted}");
        }
        else {
          return to_string("${error}");
        }
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        if ( int(id(tvoc).state) <= 660){
          return to_string("${Lightly_polluted}");
        }
        else if ( int(id(tvoc).state) >= 661 && int(id(tvoc).state) <= 1430){
          return to_string("${Moderately_polluted}");
        }
        else if ( int(id(tvoc).state) >= 1431 && int(id(tvoc).state) <= 2200){
          return to_string("${Heavily_polluted}");
        }
        else if ( int(id(tvoc).state) >= 2201 && int(id(tvoc).state) <= 3300){
          return to_string("${Severely_polluted}");
        }
        else if ( int(id(tvoc).state) >= 3301){
          return to_string("${Extremely_polluted}");
        }
        else {
          return to_string("${error}");
        }
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        if ( int(id(tvoc).state) <= 1430){
          return to_string("${Moderately_polluted}");
        }
        else if ( int(id(tvoc).state) >= 1431 && int(id(tvoc).state) <= 2200){
          return to_string("${Heavily_polluted}");
        }
        else if ( int(id(tvoc).state) >= 2201 && int(id(tvoc).state) <= 3300){
          return to_string("${Severely_polluted}");
        }
        else if ( int(id(tvoc).state) >= 3301){
          return to_string("${Extremely_polluted}");
        }
        else {
          return to_string("${error}");
        }
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        if ( int(id(tvoc).state) <= 2200){
          return to_string("${Heavily_polluted}");
        }
        else if ( int(id(tvoc).state) >= 2201 && int(id(tvoc).state) <= 3300){
          return to_string("${Severely_polluted}");
        }
        else if ( int(id(tvoc).state) >= 3301){
          return to_string("${Extremely_polluted}");
        }
        else {
          return to_string("${error}");
        }
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        if ( int(id(tvoc).state) <= 3300){
          return to_string("${Severely_polluted}");
        }
        else if ( int(id(tvoc).state) >= 3301){
          return to_string("${Extremely_polluted}");
        }
        else {
          return to_string("${error}");
        }
      }
      else if (int(id(iaq).state) >= 351) {
        if ( int(id(tvoc).state) <= 60000){
          return to_string("${Extremely_polluted}");
        }
        else {
          return to_string("${error}");
        }
      }
      else {
        return to_string("${error}");
      }
    update_interval: 1s
