sensor:
  - platform: template
    name: "${device_name} - ${Temperature}"
    id: temperature
    lambda: |-
      if (to_string("${USE_DS18B20}") == "true"){
        return id(DS18B20_temp).state;
      }
      else if (to_string("${USE_AHT}") == "true"){
        return id(aht_temp).state;
      }
      else if (to_string("${USE_BME}") == "true"){
        return id(bme_temp).state;
      }
      else if (to_string("${USE_DHT}") == "true"){
        return id(dht_temp).state;
      }
      else {
        return -99;
      }
    unit_of_measurement: ${TM}

  - platform: template
    name: "${device_name} - ${Humidity}"
    id: humidity
    lambda: |-
      if(to_string("${USE_AHT}") == "true"){
        return id(aht_hum).state;
      }
      else if (to_string("${USE_BME}") == "true"){
        return id(bme_hum).state;
      }
      else if (to_string("${USE_DHT}") == "true"){
        return id(dht_hum).state;
      }
      else {
        return -99;
      }
    unit_of_measurement: "%"
    accuracy_decimals: 0

  - platform: template
    name: "${device_name} - ${Pressure}"
    id: pressure
    lambda: |-
      if (to_string("${USE_BME}") == "true"){
        return id(bme_pres).state;
      }
      else {
        return -99;
      }

  # Absolute Humidity
  - platform: absolute_humidity
    name: "${device_name} - ${Absolute_humidity}"
    id: Absolute_Humidity
    temperature: temperature
    humidity: humidity

  # Dew point
  - platform: template
    name: "${device_name} - ${Dew_point}"
    id: Dew_Point
    lambda: |-
      return (243.5*(log(id(humidity).state/100)+((17.67*id(temperature).state)/
      (243.5+id(temperature).state)))/(17.67-log(id(humidity).state/100)-
      ((17.67*id(temperature).state)/(243.5+id(temperature).state))));
    unit_of_measurement: °C
    icon: 'mdi:thermometer-alert'

# Text_sensoren
text_sensor:

  # IAQ Classification
  - platform: template
    name: "IAQ Classification"
    icon: "mdi:seed"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return to_string("${Excellent}");
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return to_string("${Good}");
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return to_string("${Lightly_polluted}");
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return to_string("${Moderately_polluted}");
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return to_string("${Heavily_polluted}");
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return to_string("${Severely_polluted}");
      }
      else if (int(id(iaq).state) >= 351) {
        return to_string("${Extremely_polluted}");
      }
      else {
        return to_string("${error}");
      }
