---
substitutions:
  USE_BME: "true"

sensor:
  # BME680 sensor for temperature, pressure and humidity.
  # temperature and humidity data wil not be send to homeassistent
  - platform: bme680
    temperature:
      id: bme_temp
      internal: true
      unit_of_measurement: ${TM}
      oversampling: 16x
    pressure:
      id: bme_pres
      internal: true
      oversampling: 16x
    humidity:
      id: bme_hum
      internal: true
      oversampling: 16x
    i2c_id: i2c_1
    address: ${I2C_BME}
    iir_filter: 31x
    update_interval: 30s